### ISSUE TITLE
[Suggestion] Platinum progress percentage

### ISSUE THREAD

**Issue by 0915318** [carlssonemil/damascus#13]
Maybe add a platinum progress percentage bar with maybe the option to add/show also the unrequired guns for it.

**Comment by carlssonemil** [comment]
I have thought about this before, and came to the conclusion that it's not really necessary since you can clearly see under each weapon category what weapons you are missing for Platinum (indicated by the purple border, or by filtering the view to only show required weapons). With the exception of Sniper and Marksman Rifles which share the same Platinum progress.

Technically, the non-required guns for Platinum is the same as the non-required guns for the Damascus, as you need all Platinum camouflages to get the Damascus camouflage.

**Comment by 0915318** [comment]
fair enough, thanks for the reply
